### ISSUE TITLE
Tela Pré-chat

### ISSUE THREAD

**Issue by nickjng** [BabaFacil/App#10]
Tela Pré-chat
Descrição:
Desenvolvimento da tela Pre-Chat onde contém todas as conversas que o responsavel teve com as babás.

Tarefas:

Criar a pagina Pre-Chat.
Criar o card dos chat.
Organizar os card em uma FlatList para facilitar a entrada de dados.
Criar o contador de mensagens que não foram visualizadas.
Criar uma variação se quando a mensagem for nova a cor da data alterar.
Verificar se a ultima mensagem foi o usuario que enviou.
Trocar o icone e a cor dos Check se foi o usuario que mandou a ultima mensagem.

Arquivos Adicionados/Modificados:

new file: src/components/PreChatCard/index.tsx
new file: src/components/PreChatCard/styles.ts
new file: src/pages/PreChat/index.tsx
new file: src/pages/PreChat/styles.ts
modified: src/components/MenuBar.tsx
modified: src/routes/index.js
modified: src/pages/index.tsx

**Comment by Pedro-Rbeiro** [comment]
Tela Pré-chat
Descrição:
Desenvolvimento da tela Pre-Chat onde contém todas as conversas que o responsavel teve com as babás.


Tarefas:

Criar a pagina Pre-Chat.
Criar o card dos chat.
Organizar os card em uma FlatList para facilitar a entrada de dados.
Criar o contador de mensagens que não foram visualizadas.
Criar uma variação se quando a mensagem for nova a cor da data alterar.
Verificar se a ultima mensagem foi o usuario que enviou.
Trocar o icone e a cor dos Check se foi o usuario que mandou a ultima mensagem.

Arquivos Adicionados/Modificados:

new file: src/components/PreChatCard/index.tsx
new file: src/components/PreChatCard/styles.ts
new file: src/pages/PreChat/index.tsx
new file: src/pages/PreChat/styles.ts
modified: src/components/MenuBar.tsx
modified: src/routes/index.js
modified: src/pages/index.tsx
