### ISSUE TITLE
Lapidar Tela Welcome

### ISSUE THREAD

**Issue by nickjng** [BabaFacil/App#17]
Lapidar Tela Welcome
Descrição:
Será feito os ajustes finais na tela de Onboarding (Welcome), mudando os textos, adicionando ilustrações e resolvendo possiveis bugs.

Tarefas:
Alterar textos (titulo e descrição);
Alterar a estilização dos textos;
Criar e aplicar as ilustrações trocando a logo que estava para a ilustração que mais fazer sentido.

Arquivos Adicionados/Modificados:
new file: src/assets/imgs/onboarding/cradasto.png
new file: src/assets/imgs/onboarding/encontre.png
new file: src/assets/imgs/onboarding/map.png
new file: src/assets/imgs/onboarding/servico24.png
modified: src/components/Onboarding/OnboardingItem.tsx
modified: src/components/Onboarding/slides.js
modified: src/components/Onboarding/styles.ts
modified: src/components/Onboarding/Onboarding.tsx
modified: tsconfig.json

**Comment by Pedro-Rbeiro** [comment]
Lapidar Tela Welcome
Descrição:
Será feito os ajustes finais na tela de Onboarding (Welcome), mudando os textos, adicionando ilustrações e resolvendo possiveis bugs.

Tarefas:
Alterar textos (titulo e descrição);
Alterar a estilização dos textos;
Criar e aplicar as ilustrações trocando a logo que estava para a ilustração que mais fazer sentido.

Arquivos Adicionados/Modificados:
modified:   src/components/Onboarding/Onboarding.tsx
modified:   src/components/Onboarding/OnboardingItem.tsx
modified:   src/components/Onboarding/styles.ts
